apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: productinfoentities.experiments.warehouse
spec:
  group: experiments.warehouse
  names:
    kind: productinfoentity
    listKind: productinfoentityList
    plural: productinfoentities
    singular: productinfoentity
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          status:
            properties:
              status:
                type: string
            type: object
          spec:
            properties:
              description:
                description: This is a test for the contextual fetching of descriptions.
                type: string
              minimumQuantity:
                format: int32
                type: integer
              maximumQuantity:
                format: int32
                type: integer
            type: object
          metadata:
            type: object
          apiVersion:
            type: string
          kind:
            type: string
        type: object
    served: true
    storage: true
    subresources:
      status: {}
