apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: productavailabilityentities.experiments.warehouse
spec:
  group: experiments.warehouse
  names:
    kind: productavailabilityentity
    listKind: productavailabilityentityList
    plural: productavailabilityentities
    singular: productavailabilityentity
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          status:
            properties:
              status:
                type: string
            type: object
          spec:
            properties:
              availableQuantity:
                description: This is a test for the contextual fetching of descriptions.
                format: int32
                type: integer
            type: object
          metadata:
            type: object
          apiVersion:
            type: string
          kind:
            type: string
        type: object
    served: true
    storage: true
    subresources:
      status: {}
