apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-role
rules:
- apiGroups:
  - experiments.warehouse
  resources:
  - productavailabilityentities
  verbs:
  - '*'
- apiGroups:
  - experiments.warehouse
  resources:
  - productavailabilityentities/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - experiments.warehouse
  resources:
  - productinfoentities
  verbs:
  - '*'
- apiGroups:
  - experiments.warehouse
  resources:
  - productinfoentities/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - '*'
